#!/bin/bash -l

# jobname
#SBATCH --job-name=x4

# number of repetitions
# repeat=2

# MPI tasks
#SBATCH --ntasks-per-node=32

# number of nodes
#SBATCH --nodes=3

# mail-notification
#SBATCH --mail-user=Manuel.Lippert@uni-bayreuth.de
#SBATCH --mail-type=END

# walltime
#              d-hh:mm:ss
#SBATCH --time=0-24:00:00

# execute the job
time mpirun -np $SLURM_NTASKS ./gkw.x > output.dat

# end
exit 0
