#! /bin/tcsh
# Script to move the results of a run in the standard GKW folder architecture


if ( $#argv == 0 ) then
  echo For usage call with --help
  exit(0)
endif

if ( "x$argv[1]" == "x-h" || "x$argv[1]" == "x-help" || "x$argv[1]" == "x-v" || "x$argv[1]" == "x--help" ) then
  echo '***********************************************'
  echo Script that moves the results of a GKW run in the standard folder architecture
  echo 
  echo 'Usage:'
  echo       gkwmv_babel [-t] runname
  echo 
  echo Always run the script in the runs directory  of the project folder
  echo '***********************************************'
  exit(0)
endif 

cd ..
set gkwroot=`pwd`
if ( ! -e input ) then 
  echo "NO input directory found, did you execute inside runs? "
  exit(1)
endif 
if ( ! -e time ) then 
  echo "NO time directory found, did you execute inside runs? "
  exit(1)
endif 
if ( ! -e fluxes ) then 
  echo "NO fluxes directory found, did you execute inside runs? "
  exit(1)
endif 
if ( ! -e runs ) then 
  echo "NO runs directory found, did you execute inside runs? "
  exit(1)
endif 

set untar=0
if ( "$argv[1]" == "-t" ) then
      set untar=1
      shift
else
      set untar=0
endif


while ($#argv)
  if ( ! -d $gkwroot/runs/$argv[1] ) then
    echo  $argv[1] : folder does not exist
  else
    if ( ! -e $gkwroot/runs/$argv[1]/$argv[1].tar ) then
      echo  $argv[1].tar : file does not exist
    else
     set rundir=$gkwroot/runs/$argv[1]
     cd $rundir

     if ( $untar == 1) then
       tar -xf $argv[1].tar
     endif
   
     mv $rundir/*.o $gkwroot/out/pbs/$argv[1].o
     mv $rundir/*.e $gkwroot/out/pbs/$argv[1].e
     mv $rundir/parallel_phi.dat $gkwroot/parallel/phi_time/$argv[1]
     mv $rundir/parallel_apar.dat $gkwroot/parallel/apar_time/$argv[1]
     mv $rundir/time.dat $gkwroot/time/$argv[1]
     mv $rundir/distr1.dat $gkwroot/distr1/$argv[1]
     mv $rundir/distr2.dat $gkwroot/distr2/$argv[1]
     mv $rundir/distr3.dat $gkwroot/distr3/$argv[1]
     mv $rundir/distr4.dat $gkwroot/distr4/$argv[1]
     #Note rename commmand may differ on machines.
     rename distr3 $argv[1] distr3.*
     mv $rundir/$argv[1].sp* $gkwroot/distr3
     rename distr4 $argv[1] distr4.*
     mv $rundir/$argv[1].sp* $gkwroot/distr4
     mv $rundir/fluxes.dat $gkwroot/fluxes/$argv[1]
     mv $rundir/geom.dat $gkwroot/geom/$argv[1]
     mv $rundir/fluxes_em.dat $gkwroot/fluxes/em/$argv[1]
     mv $rundir/fluxes_bpar.dat $gkwroot/fluxes/bpar/$argv[1]
     mv $rundir/kyspec $gkwroot/spectrum/kyspec/$argv[1]
     mv $rundir/kxspec $gkwroot/spectrum/kxspec/$argv[1]
     mv $rundir/kxvort $gkwroot/spectrum/kxvort/$argv[1]
     mv $rundir/kyvort $gkwroot/spectrum/kyvort/$argv[1]
     mv $rundir/kyspec_em $gkwroot/spectrum/kyspec_em/$argv[1]
     mv $rundir/kxspec_em $gkwroot/spectrum/kxspec_em/$argv[1]
     mv $rundir/pflux_spectra.dat $gkwroot/spectrum/pflux/$argv[1]
     mv $rundir/eflux_spectra.dat $gkwroot/spectrum/eflux/$argv[1]
     mv $rundir/vflux_spectra.dat $gkwroot/spectrum/vflux/$argv[1]
     mv $rundir/pflux_xspec.dat $gkwroot/spectrum/pflux_kx/$argv[1]
     mv $rundir/eflux_xspec.dat $gkwroot/spectrum/eflux_kx/$argv[1]
     mv $rundir/vflux_xspec.dat $gkwroot/spectrum/vflux_kx/$argv[1]
     mv $rundir/pflux_em_spectra.dat $gkwroot/spectrum/pflux_em/$argv[1]
     mv $rundir/eflux_em_spectra.dat $gkwroot/spectrum/eflux_em/$argv[1]
     mv $rundir/vflux_em_spectra.dat $gkwroot/spectrum/vflux_em/$argv[1]
     mv $rundir/pflux_em_xspec.dat $gkwroot/spectrum/pflux_em_kx/$argv[1]
     mv $rundir/eflux_em_xspec.dat $gkwroot/spectrum/eflux_em_kx/$argv[1]
     mv $rundir/vflux_em_xspec.dat $gkwroot/spectrum/vflux_em_kx/$argv[1]
     cp $rundir/krho $gkwroot/spectrum/kyspec/$argv[1].krho
     cp $rundir/kxrh $gkwroot/spectrum/kxspec/$argv[1].kxrh
     mkdir $gkwroot/spectrum/phi/$argv[1]
     mkdir $gkwroot/spectrum/spc/$argv[1]
     mkdir $gkwroot/spectrum/vok/$argv[1]
     mkdir $gkwroot/restart/$argv[1]
     mv $rundir/xphi $gkwroot/spectrum/phi/$argv[1]/xphi
     mv $rundir/yphi $gkwroot/spectrum/phi/$argv[1]/yphi
     mv $rundir/krho $gkwroot/spectrum/spc/$argv[1]/krho
     mv $rundir/kxrh $gkwroot/spectrum/spc/$argv[1]/kxrh
     rm $rundir/input.dat
     #Beware the following lines can mean large amount of data movement!
       mv $rundir/phi* $gkwroot/spectrum/phi/$argv[1]
       mv $rundir/spc* $gkwroot/spectrum/spc/$argv[1]
       mv $rundir/vok* $gkwroot/spectrum/vok/$argv[1]
       mv $rundir/F* $gkwroot/restart/$argv[1]
       mv $rundir/DM* $gkwroot/restart/$argv[1]
     #End beware
     mv $rundir/input.out $gkwroot/out/$argv[1].out
     rm $rundir/gkw
     mv $rundir/par.dat $gkwroot/par/$argv[1]
     mv $rundir/parfun.dat $gkwroot/par/$argv[1].fun
     mv $rundir/out $gkwroot/out/$argv[1]
     rm parallel_rebuild.sh
     rm par00*
     mv $rundir/parallel.dat $gkwroot/parallel/$argv[1]
     mkdir $gkwroot/other/$argv[1]
     mv $rundir/*.dat $gkwroot/other/$argv[1]

    endif
  endif
  shift
end
  
cd $gkwroot/runs
