#!/bin/bash
# Removes some (unimportant ?) input parameters that not allowed in the input file for new GS2
cp $1 $1.old
perl -p -i -n -e 's/vmom_eq/vmom_eq/g' $1
perl -p -i -n -e 's/vmom_eq/!vmom_eq/g' $1
perl -p -i -n -e 's/norm_option/!norm_option/g' $1 #Warning this changes values!
perl -p -i -n -e 's/upara/!upara/g' $1   #Warning this should go into Mach?
perl -p -i -n -e 's/Ecut/!Ecut/g' $1
perl -p -i -n -e 's/conserve/!conserve/g' $1  
#Warning this might affect values - the new versions conserve everything by default
perl -p -i -n -e 's/collision_model.*$/collision_model='lorentz'/g' $1 #pitch angle only

#It seems all these diagnostic switches are gone - into netcdf?
 perl -p -i -n -e 's/write_phi/!write_phi/g' $1
 perl -p -i -n -e 's/write_apa/!write_apa/g' $1
 perl -p -i -n -e 's/write_apar/!write_apar/g' $1
 perl -p -i -n -e 's/write_aperp/!write_aperp/g' $1
 perl -p -i -n -e 's/write_qheat/!write_qheat/g' $1
 perl -p -i -n -e 's/write_pflux/!write_pflux/g' $1
 perl -p -i -n -e 's/write_vflux/!write_vflux/g' $1
 perl -p -i -n -e 's/write_qmheat/!write_qmheat/g' $1
 perl -p -i -n -e 's/write_pmflux/!write_pmflux/g' $1
 perl -p -i -n -e 's/write_vmflux/!write_vmflux/g' $1
 perl -p -i -n -e 's/write_dmix/!write_dmix/g' $1
 perl -p -i -n -e 's/write_kperpnorm/!write_kperpnorm/g' $1
 perl -p -i -n -e 's/write_lamavg/!write_lamavg/g' $1
 perl -p -i -n -e 's/write_eavg/!write_eavg/g' $1
 perl -p -i -n -e 's/write_tavg/!write_tavg/g' $1
 perl -p -i -n -e 's/write_fieldline/!write_fieldline/g' $1
 perl -p -i -n -e 's/write_neoclassical/!write_neoclassical/g' $1
 perl -p -i -n -e 's/dump_neoclassical/!dump_neoclassical/g' $1
 perl -p -i -n -e 's/write_fcheck/!write_fcheck/g' $1
 perl -p -i -n -e 's/write_fieldcheck/!write_fieldcheck/g' $1
 perl -p -i -n -e 's/print_old_units/!print_old_units/g' $1
