#!/bin/bash
#This script is designed to stop all runs in a project
#Useful if your runs are getting near their walltime
#or someone threatens to shutdown the cluster.
#This way the final output data is written so you can restart.
#Run from the top level of the project folder.

cd runs        

TXT=""
echo "Loop over directories" $TXT"*"

#ls | grep $TXT

# echo 'Warning: This script will stop all currently running jobs from the directories above.   Proceed? y/n:'
#   read OPTION
# 
#   if [ $OPTION != 'y' ]
#     then
#     echo 'abort'
#     exit
#   fi

for i in $( ls -p | grep /)
	do
		echo $i
		cd $i
                mv input.dat gkw.stop
		cd ..
		
	done

