#! /bin/bash
## To run the GKW tests on helios, submit this job script
## can submit directly from home does not need to be on scratch
#PBS -v OMP_NUM_THREADS=1
#PBS -V
#PBS -N tests
#SBATCH --time=01:00:00
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=1
#SBATCH -A RESIDUAL 
  
export GKW_HOME=`pwd`/../
module load bullxmpi intel fftw/3.3.3 petsc/3.5.3/complex slepc/3.5.3/complex
export OMP_NUM_THREADS=1

$GKW_HOME/scripts/gkw_run_tests -p > tests.out

now=$(date +%F_%T)
cp tests.out $GKW_HOME/tests${now}.out
