#!/bin/bash

# use this script interactively or like this:

#switch-testcase-parameters <<EOF
#io_legacy
#CONTROL
#.false.
#y
#EOF

# If no cmd line argument is given, use the default value
folder=${1:-"$GKW_HOME/tests/standard"}

function read-yesno(){
    varname="$1"

    while true; do
	read tmp
	if [ "$tmp" == "y" ]; then
	    eval $varname="y"
	    return
	else
	    eval $varname="n"
	    return
	fi
    done
}

echo "Please enter the name of the parameter which shall be set for all testcases in $folder:"
read paramname

echo "Please enter the name of the namelist this parameter belongs to (in uppercase please, e.g. CONTROL):"
read namelist

echo "Which value shall be applied to all $paramname parameters?"
read value

# set the value wherever the parameter exists already

for file in $(grep --recursive --include=input.dat --ignore-case --files-with-matches $paramname $folder)
do
	if [ -f "$file" ]
	then
	   echo "'$file' is a file. Apply the setting."
	   sed -i "s/$paramname.*/$paramname = $value/I" "$file"
	fi	   
done

echo "Do you want to set the value also in inputfiles where it is not listed explicitely at the moment? [y/n]"
read-yesno answer


if [ "$answer" == "y" ]
then

    # If that namelist does not exist yet, then append it to the end of the input file.
    for file in $(grep --recursive --include=input.dat --ignore-case --files-without-match "&$namelist" $folder)
    do
	echo "Put the namelist $namelist into $file."
	cat <<EOF >> $file
&$namelist
/
EOF
    done

    # Try to do it in a nice way, so that it can be committed without
    # further editing, if desired.
    
    #put the entry into the namelist
    for file in $(grep --recursive --include=input.dat --ignore-case --files-without-match $paramname $folder)
    do
	if [ -f "$file" ]
	then
	    echo "'$file' is a file. Apply the setting."
	    #sed -i "s/&$namelist.*/&\n $paramname = $value/" "$file"

	    #Do the replacement, but only on blocks of text beginning
	    #with a line containing $namelist, and ending with a line
	    #containing only a forward slash, inclusive.

	    sed -i -e "/\&$namelist.*/,/^ *\//s/^ *\// $paramname = $value\n\//Ig" "$file"
	    #/beginpattern/,/endpattern/s/matchpattern/replpattern/g

	fi	   
    done
fi
